module.exports = {
  'users.list' : {url : '/_api/users.list', method : 'GET', },
  'pages.list' : {url : '/_api/pages.list', method : 'GET', },
  'pages.create' : {url : '/_api/pages.update', method : 'POST', },
  'pages.get' : {url : '/_api/pages.get', method : 'GET', },
  'pages.updatePost' : {url : '/_api/pages.updatePost', method : 'GET', },
  'pages.seen' : {url : '/_api/pages.seen', method : 'POST', },
  'pages.rename' : {url : '/_api/pages.rename', method : 'POST', },
  'comments.get' : {url : '/_api/comments.get', method : 'GET', },
  'comments.add' : {url : '/_api/comments.add', method : 'POST', },
  'bookmarks.get' : {url : '/_api/bookmarks.get', method : 'GET', },
  'bookmarks.add' : {url : '/_api/bookmarks.add', method : 'POST', },
  'bookmarks.remove' : {url : '/_api/bookmarks.remove', method : 'POST', },
  'likes.add' : {url : '/_api/likes.add', method : 'POST', },
  'likes.remove' : {url : '/_api/likes.remove', method : 'POST', },
  'attachments.list' : {url : '/_api/attachments.list', method : 'GET', },
  'attachments.add' : {url : 'attachments.add', method : 'POST', },
  'attachments.remove' : {url : '/_api/attachments.remove', method : 'POST', },
  'revisions.get' : {url : '/_api/revisions.get', method : 'GET', },
  'revisions.ids' : {url : '/_api/revisions.ids', method : 'GET', },
  'revisions.list' : {url : '/_api/revisions.list', method : 'GET', },
};
